name: Build the base container image

on:
  pull_request:
    branches:
      - main

    paths:
      - Payload_Type/thanatos/thanatos/agent_code
      - Payload_Type/thanatos/**.py

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build the base container image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build the container image
        uses: docker/build-push-action@v5
        with:
          context: Payload_Type/thanatos
          file: Payload_Type/thanatos/.docker/Dockerfile
          tags: testing
          push: false
